services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.10-alpine
    container_name: woodpecker-server
    restart: unless-stopped
    expose:
      - "${WOODPECKER_SERVER_ADDR}" # Web UI
      - "${WOODPECKER_GRPC_ADDR}" # RPC for agent to connect
    env_file:
      - .env
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
      - ${DIR_PATH}:${DIR_PATH}
    networks:
      - application_network

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.10-alpine
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DIR_PATH}:${DIR_PATH}
    networks:
      - application_network

volumes:
  woodpecker-server-data:

networks:
  application_network:
    external: true
