services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.10-alpine
    container_name: woodpecker-server
    restart: unless-stopped
    expose:
      - "8001" # Web UI
      - "8002" # RPC for agent to connect
    env_file:
      - .env
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
    networks:
      - application_network

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.10-alpine
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - application_network

volumes:
  woodpecker-server-data:

networks:
  application_network:
    external: true
